var SCHOOLS = [
    {
        name: 'Sunset Valley',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "M1",
    },{
        name: 'Rodriguez',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "M1",
    },{
        name: 'Hart',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "T1",
    },{
        name: 'Perez',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "W1",
    },{
        name: 'Padron',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "W1",
    },{
        name: 'Andrews',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "R1",
    },{
        name: 'Galindo',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "R1",
    },{
        name: 'Blanton',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "R1",
    },{
        name: 'Boys and Girls Club',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "M2",
    },{
        name: 'NYOS M',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "T2",
    },{
        name:  'Martin',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "T2",
    },{
        name:  'Ponzu',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "W2",
    },{
        name:  'Kitty',
        students: 0, 
        rides: 0,
        studentList: [],
        capacity: 10,
        time: "R2",
    },{
      name:  'Unsorted',
      students: 0, 
      rides: 0,
      studentList: [],
      capacity: 999,
      time: "unsorted",
  },
];

var TIMES = [ 
    {id: 'M1', timeName: 'Monday 2:30-4:30', orange: true, 
      schools: []},
    {id: 'T1', timeName: 'Tuesday 2:30-4:30', orange: false, 
      schools: []},
    {id: 'W1', timeName: 'Wednesday 2:30-4:30', orange: true, 
      schools: []},
    {id: 'R1', timeName: 'Thursday 2:30-4:30', orange: false, 
      schools: []},
    {id: 'M2', timeName: 'Monday 3:30-5:30', orange: false, 
      schools: []},
    {id: 'T2', timeName: 'Tuesday 3:30-5:30', orange: true, 
      schools: []},
    {id: 'W2', timeName: 'Wednesday 3:30-5:30', orange: false, 
      schools: []},
    {id: 'R2', timeName: 'Thursday 3:30-5:30', orange: true, 
      schools: []},
    {id: 'unsorted', timeName: 'Unsorted', orange: false, 
    schools: []},
  ];

const timeSlotMap = {
  "M1": "monday1",
  "M2": "monday2",
  "T1": "tuesday1",
  "T2": "tuesday2",
  "W1": "wednesday1",
  "W2": "wednesday2",
  "R1": "thursday1",
  "R2": "thursday2",
  "F1": "friday1",
  "F2": "friday2"
};
export {SCHOOLS, TIMES, timeSlotMap};